export const HTTP_OK = 200;
export const HTTP_MULTIPLE_CHOICES = 300;
export const HTTP_BAD_REQUEST = 400;
export const HTTP_UNAUTHORIZED = 401;
export const HTTP_FORBIDDEN = 403;
export const HTTP_NOT_FOUND = 404;
export const HTTP_CONFLICT = 409;
export const HTTP_TOO_MANY_REQUESTS = 429;
export const HTTP_INTERNAL_SERVER_ERROR = 500;
export const HTTP_BAD_GATEWAY = 502;
export const HTTP_SERVICE_UNAVAILABLE = 503;

export const TESTIMONIAL_PULSE_START_DELAY_MS = 3000;
export const TESTIMONIAL_PULSE_INTERVAL_MS = 7000;
export const EMAIL_SENT_DIALOG_CLOSE_DELAY_MS = 1200;
export const SAVED_INDICATOR_DURATION_MS = 1500;

export const CAPTCHA_POLL_INTERVAL_MS = 100;
export const CAPTCHA_POLL_ATTEMPTS = 20;

export const CAPTCHA_RETRY_DELAY_MS = 750;

export const HEALTH_CHECK_TIMEOUT_MS = 3000;

export const MAX_ATTACHMENT_BYTES = 10 * 1024 * 1024;
export const MAX_TEXT_LENGTH = 500_000;

export const MAX_SAVED_ITEM_NAME_LENGTH = 100;

export const MAX_SLUG_ATTEMPTS = 20;

export const RESUMES_PAGE_SIZE = 12;
export const COVER_LETTERS_PAGE_SIZE = 12;

export const FREE_TIER_LIMITS = {
  resumes: 2,
  coverLetters: 2,
};

export const RATE_LIMIT_SEND_EMAIL_REQUESTS = 5;
export const RATE_LIMIT_SEND_EMAIL_WINDOW = "10 m";
export const RATE_LIMIT_ACCOUNT_EXPORT_REQUESTS = 10;
export const RATE_LIMIT_ACCOUNT_EXPORT_WINDOW = "1 h";
export const RATE_LIMIT_ACCOUNT_DELETE_REQUESTS = 5;
export const RATE_LIMIT_ACCOUNT_DELETE_WINDOW = "1 h";
export const RATE_LIMIT_STRIPE_CHECKOUT_REQUESTS = 10;
export const RATE_LIMIT_STRIPE_CHECKOUT_WINDOW = "1 h";
export const RATE_LIMIT_STRIPE_CANCEL_REQUESTS = 10;
export const RATE_LIMIT_STRIPE_CANCEL_WINDOW = "1 h";

export const MIN_COVER_LETTER_BODY_LENGTH = 200;
export const KEYWORD_EXTRACTION_LIMIT = 30;

export const MAX_COHERENCE_CHECK_TEXT_LENGTH = 10_000;
export const RATE_LIMIT_ATS_COHERENCE_REQUESTS = 3;
export const RATE_LIMIT_ATS_COHERENCE_WINDOW = "10 m";

export const MAX_AI_REWRITE_TEXT_LENGTH = 10_000;
export const RATE_LIMIT_AI_REWRITE_REQUESTS = 10;
export const RATE_LIMIT_AI_REWRITE_WINDOW = "10 m";

export const MAX_IMPORT_FILE_BYTES = 5 * 1024 * 1024;
export const MAX_IMPORT_EXTRACTED_TEXT_LENGTH = 8_000;
export const RATE_LIMIT_IMPORT_RESUME_REQUESTS = 5;
export const RATE_LIMIT_IMPORT_RESUME_WINDOW = "10 m";

export const ANONYMOUS_ACCOUNT_RETENTION_DAYS = 7;

export const RATE_LIMIT_SHARED_DOCUMENT_REQUESTS = 30;
export const RATE_LIMIT_SHARED_DOCUMENT_WINDOW = "10 m";

export const SHARE_LINK_EXPIRATION_DAYS = 30;

export const BLOG_POSTS_CACHE_TAG = "blog-posts";
export const BLOG_POSTS_CACHE_REVALIDATE_SECONDS = 3600;

export const SUPPORT_EMAIL = "support@quickresumebuilder.online";

export const RATE_LIMIT_IMPORT_COVER_LETTER_REQUESTS = 5;
export const RATE_LIMIT_IMPORT_COVER_LETTER_WINDOW = "10 m";
